apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: lock-managed-resource-mutations
spec:
  policyName: openbao-operator-lock-managed-resource-mutations
  validationActions:
    - Deny
