apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: openbao-restrict-sentinel-mutations
spec:
  policyName: openbao-restrict-sentinel-mutations
  validationActions:
    - Deny
