apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: validate-openbao-tenant
spec:
  policyName: validate-openbao-tenant
  validationActions:
    - Deny
