apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: validate-openbaorestore
spec:
  policyName: openbao-operator-validate-openbaorestore
  validationActions:
    - Deny

