apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  labels:
    app.kubernetes.io/name: openbao-operator
    app.kubernetes.io/component: controller
spec:
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
      name: webhook-server
  selector:
    app.kubernetes.io/name: openbao-operator
    app.kubernetes.io/component: controller
