apiVersion: v2
name: openbao-operator
description: OpenBao Operator installs the OpenBao Kubernetes operator and its required cluster-scoped resources.
type: application
version: 0.0.0
appVersion: v0.0.0
icon: https://openbao.org/img/logo.svg
home: https://github.com/dc-tec/openbao-operator
sources:
  - https://github.com/dc-tec/openbao-operator
keywords:
  - openbao
  - vault
  - secrets
  - operator
  - kubernetes
maintainers:
  - name: dc-tec
    url: https://github.com/dc-tec
kubeVersion: ">=1.33.0-0"
