resources:
  - provisioner_monitor.yaml
  - controller_monitor.yaml
# [PROMETHEUS-WITH-CERTS] The following patch configures the ServiceMonitors in ../prometheus
# to securely reference certificates created and managed by cert-manager.
# Additionally, ensure that you uncomment the [METRICS WITH CERTMANAGER] patch under config/default/kustomization.yaml
# to mount the "metrics-server-cert" secret in the Manager Deployments.
#patches:
#  - path: monitor_tls_patch.yaml
#    target:
#      kind: ServiceMonitor
