apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openbao-operator-controller-openbaorestore-rolebinding
  labels:
    app.kubernetes.io/name: openbao-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: kustomize
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openbao-operator-controller-openbaorestore-role
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: system
