apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: openbao-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: kustomize
  name: controller
  namespace: system
