{{- if eq .Values.tenancy.mode "multi" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openbao-operator.provisionerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbao-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
  {{- with .Values.provisioner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openbao-operator.provisionerDelegateServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openbao-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: provisioner
{{- end }}

